# title del head
title: "eFrolic"
subtitle: "It is the party of developers, simple and modern."

# description
description: "It is a CSS framework, which without using javascript is interactive and animated.
This framework is based on being modular and simple to develop web interfaces focused on mobile devices."

# twitter
twitter: "https://twitter.com/e_frolic"

# Config
button: anime primary
button_secondary: anime inverted primary
button_optional: anime inverted danger
button_header: anime inverted danger
text_color: rgba(0, 0, 0, .5)
bg_color: white
title_color: 1da1f2

# Page default
lang: en
ref: hello

# Build settings
markdown: kramdown
url: https://efraperalta.github.io/eFrolic-jekyll
permalink: pretty
exclude: ['node_modules', 'gulpfile.js', 'package-lock.json', 'Gemfile', 'Gemfile.lock', 'feed.xml']
